export const socials = {
    github: "https://github.com/anurag-327",
    linkedin: "https://www.linkedin.com/in/anuragsr327",
    twitter: "https://twitter.com/itsAnurag_sri",
    resume: "https://drive.google.com/file/d/1WoYeVM3G7EWqdT29T4odE83zOQe10vEG/view",
    instagram: "#",
    codechef: "https://www.codechef.com/users/anurag_cp273",
    leetcode: "https://leetcode.com/Anurag_sr/",
};

const hackfinder_logo = "/projects/hackfinder.svg";
const quicksign_logo = "/projects/quicksign.svg";
const codemon_logo = "/projects/codemon.svg";
const vault_logo = "/projects/vault.svg";
const pint_logo = "/projects/pint.svg";
const socicons_logo = "/projects/socicons.svg";
const logger_logo = "/projects/logger.svg";
const anubhuti_logo = "/projects/anubhuti.svg";
const chatapp_logo = "/projects/chatapp.svg";
const notesapp_logo = "/projects/notes.svg";
const ecommerce_logo = "/projects/ecommerce.svg";
const quicksign = "/projectimages/quicksign.png";
const codemon = "/projectimages/codemon3.png";
const hackfinder = "/projectimages/hackfinder.png";
const vault = "/projectimages/vault.png";
const pint = "/projectimages/pint.png";
const socicons = "/projectimages/socicons.png";
const logger = "/projectimages/logger.png";

const neuron = "/projectimages/neuron.png";
export const projects = [
    {
        id: 1,
        name: "QuickSign",
        tag: "OAuth Provider for seamless User Sign-ups across",
        description: "An OAuth Provider utilizing React, Node.js, Express, and MongoDB to streamline user authentication. It offers a seamless, secure sign-up process across multiple platforms, integrating robust state management for an optimized user experience.",
        toolsused: "NodeJs, MongoDB",
        logo: quicksign_logo,
        image: quicksign,
        code: "https://github.com/anurag-327/QuickSign",
        link: "https://quick-sign.vercel.app",
        points: [
            "Designed a custom OAuth provider to facilitate seamless user sign-ups across client applications.",
            "Efficiently handled secure user authentication and session management with Node.js and Express.js.",
            "Integrated MongoDB for scalable data storage and user state management.",
        ],
        stack: "React",
        stack_logo: "https://d26c7l40gvbbg2.cloudfront.net/tool_icons/reactjs.svg",
    },
    {
        id: 2,
        name: "codemon",
        tag: "A Web-based IDE for CPP Compilation and DSA Problem Solving",
        description: "A comprehensive web-based IDE designed for C++ compilation and DSA problem-solving. Built with Next.js and Zustand for state management, it features a custom backend API using Express.js and MongoDB to handle secure code execution.",
        toolsused: "NodeJs, MongoDB",
        logo: codemon_logo,
        image: codemon,
        code: "https://github.com/anurag-327/codemon",
        link: "https://codemon-five.vercel.app/",
        points: [
            "Developed a versatile web-based IDE for running CPP codes, DSA problem-solving, and debugging.",
            "Managed complete state of the app with Zustand library",
            "Constructed APIs using Express.js, Node.js, and MongoDB to facilitate code execution and management.",
        ],
        stack: "Next JS",
        stack_logo: "https://d26c7l40gvbbg2.cloudfront.net/tool_icons/nextjs.svg",
    },
    {
        id: 3,
        name: "logger",
        tag: "Visitor Tracking and Analytics Tool with Privacy in Mind",
        description: `A privacy-focused visitor tracking tool providing real-time analytics without intrusion. Engineered for scalability using Next.js and Supabase, it efficiently handles varying traffic loads while delivering actionable insights.`,
        toolsused: "Next JS, Zustand, supabase",
        logo: logger_logo,
        image: logger,
        code: "https://github.com/anurag-327/logger",
        link: "https://logger-mocha-six.vercel.app/",
        points: [
            "Developed and implemented a non-intrusive visitor counting system, Logger, for websites",
            "Engineered Logger to be scalable, accommodating varying levels of website traffic, while optimizing performance for resource efficiency.",
            "Integrated Supabase for streamlined and real-time data management in the Logger project, ensuring efficiency and ease of use.",
        ],
        stack: "Next JS",
        stack_logo: "https://d26c7l40gvbbg2.cloudfront.net/tool_icons/nextjs.svg",
    },
    {
        id: 12,
        name: "Anubhuti",
        tag: "Engaging website for college fest Anubhuti, showcasing events and info.",
        description: "The official website for 'Anubhuti', a college fest, designed to showcase events and schedules. Built with a mobile-first approach using Tailwind CSS and Next.js, backed by Supabase for real-time event management.",
        toolsused: "Next.js, Tailwind CSS, Supabase",
        logo: anubhuti_logo,
        image: null,
        code: "https://github.com/ashishk1331/Anubhuti-2K24",
        link: "https://anubhuti24.in/",
        points: [
            "Crafted a user-friendly interface with Next.js and Tailwind CSS.",
            "Implemented responsive design for optimal viewing on all devices.",
            "Integrated event details and schedules using Supabase for easy access and navigation.",
        ],
        stack: "Next.js, Tailwind CSS, Supabase",
        stack_logo: "https://d26c7l40gvbbg2.cloudfront.net/tool_icons/nextjs.svg",
    },
    {
        id: 4,
        name: "socions",
        tag: "A Library for Generating Icons of Brands and Tech Stacks",
        description: "An open-source library for generating high-quality SVG icons for popular brands and tech stacks. Published as an NPM package, it simplifies icon integration for developers across web and mobile platforms.",
        toolsused: "Svg, npm package, esbuild, javascript",
        logo: socicons_logo,
        image: socicons,
        code: "https://github.com/anurag-327/socions",
        link: "https://www.npmjs.com/package/socicons",
        points: [
            "Created Socions, an icon library featuring logos of well-known brands, social media platforms, and popular tech stacks",
            "Diverse icon support, including social media (e.g., Facebook, Twitter) and tech stacks (e.g., JavaScript, Python)",
            "User-friendly design for seamless icon integration in web and mobile apps",
        ],
        stack: "Npm",
        stack_logo: "https://img.icons8.com/color/48/npm.png",
    },
    {
        id: 5,
        name: "Vault",
        description: "A secure password manager ensuring sensitive data protection through robust encryption. Features a modern UI with Radix primitives and Tailwind CSS, utilizing Appwrite Cloud for secure authentication and storage.",
        toolsused: "React, Express js, Node Js, MongoDB",
        logo: vault_logo,
        image: vault,
        code: "https://github.com/anurag-327/PasswordManager",
        link: "https://my-vault-pm.vercel.app",
        points: [
            "Handled authentication and storage for the app with Appwrite Cloud services",
            "Managed user data and app data with Zustand",
            "Used Tailwind CSS and radix UI for accessible and configurable components.",
        ],
        stack: "React",
        stack_logo: "https://d26c7l40gvbbg2.cloudfront.net/tool_icons/reactjs.svg",
    },
    {
        id: 6,
        name: "Pint",
        description: `A creative utility app that wraps screenshots in beautiful, customizable gradient backgrounds. Built with Next.js and Tailwind CSS, focusing on aesthetic presentation for social media sharing.`,
        toolsused: "Next JS, Tailwind CSS, appwrite",
        logo: pint_logo,
        image: pint,
        code: "https://github.com/ashishk1331/Pint",
        link: "https://pint-blue.vercel.app/",
        points: [
            "Securedly stored and managed credentials with strong encryption methods.",
            "Safeguarded sensitive information, ensuring data protection and security.",
            "Ensured data security and user data protection through robust encryption methods.",
        ],
        stack: "Next JS",
        stack_logo: "https://d26c7l40gvbbg2.cloudfront.net/tool_icons/nextjs.svg",
    },
    {
        id: 7,
        name: "Hack Finder",
        description: `A platform connecting enthusiasts with hackathons globally. Simplifies the discovery process with a clean UI and powerful search capabilities, fostering a vibrant community of developers.`,
        toolsused: "Next JS, Tailwind CSS, supabase",
        logo: hackfinder_logo,
        image: hackfinder,
        code: "https://github.com/anurag-327/hackfinder",
        link: "https://hackfinder.vercel.app/",
        points: [],
        stack: "Next JS",
        stack_logo: "https://d26c7l40gvbbg2.cloudfront.net/tool_icons/nextjs.svg",
    },
    {
        id: 8,
        name: "Chat App",
        description: "A real-time messaging application enabling one-on-one conversations. Built on the MERN stack with Socket.io for instant message delivery and seamless connectivity.",
        toolsused: "React, Express js, Node Js, MongoDB",
        logo: chatapp_logo,
        image: "",
        code: "https://github.com/anurag-327/Chat-App",
        link: "",
        points: [],
        stack: "React",
        stack_logo: "https://d26c7l40gvbbg2.cloudfront.net/tool_icons/reactjs.svg",
    },
    {
        id: 9,
        name: "E-Commerce Website",
        description: "A fully functional e-commerce platform featuring product browsing, cart management, and checkout flows. Demonstrates full-stack capabilities using React and a custom Node.js/MongoDB backend.",
        toolsused: "React, Express js, Node Js, MongoDB",
        logo: ecommerce_logo,
        image: "",
        code: "https://github.com/anurag-327/E-Commerce",
        link: "",
        points: [],
        stack: "React",
        stack_logo: "https://d26c7l40gvbbg2.cloudfront.net/tool_icons/reactjs.svg",
    },
    {
        id: 11,
        name: "Google Keep Clone",
        description: "A replica of Google Keep providing robust note-taking capabilities. Supports creating, editing, deleting, and archiving notes with a clean, familiar interface.",
        toolsused: "HTML, CSS, JS, EJS, Express js, MongoDB",
        logo: notesapp_logo,
        image: "",
        code: "https://github.com/anurag-327/Google-Keep-Notes",
        link: "",
        points: [],
        stack: "Javascript",
        stack_logo: "https://img.icons8.com/color/48/javascript--v1.png",
    },
    {
        id: 10,
        name: "Car Rental System",
        description: "A web-based management system for car rentals, allowing users to browse available vehicles and book rentals for short periods. Features a comprehensive admin dashboard.",
        toolsused: "HTML, CSS, JS, EJS, Express js, MongoDB",
        logo: "",
        image: "",
        code: "https://github.com/anurag-327/Car-Rental-System",
        link: "",
        points: [],
        stack: "Javascript",
        stack_logo: "https://img.icons8.com/color/48/javascript--v1.png",
    },
    {
        id: 13,
        name: "Netflix UI Clone",
        description: "A pixel-perfect recreation of the Netflix user interface. Focuses on advanced CSS techniques and responsive design principles to mimic the streaming giant's look and feel.",
        toolsused: "HTML, CSS, JS",
        logo: "",
        image: "",
        code: "https://github.com/anurag-327/Netflix-UI-clone",
        link: "",
        points: [],
        stack: "HTML",
        stack_logo: "https://d26c7l40gvbbg2.cloudfront.net/tool_icons/reactjs.svg",
    },
    {
        id: 14,
        name: "ImgHost",
        description: "A simple image hosting platform allowing users to upload images and receive direct links for sharing. Built with Multer for handling file uploads efficiently.",
        toolsused: "Express js, Node Js, MongoDB, Multer, EJS",
        logo: "",
        image: "",
        code: "https://github.com/anurag-327/Imghost",
        link: "",
        points: [],
        stack: "Multer",
        stack_logo: "https://img.icons8.com/color/48/javascript--v1.png",
    },
];

export const currentProjects = [
    {
        id: 1,
        name: "Neuron",
        tag: "OAuth Provider for seamless User Sign-ups across",
        description: "A high-performance, managed code execution engine that lets you run untrusted user code securely and instantly.",
        toolsused: "Go, Docker, Redis",
        logo: null,
        image: neuron,
        code: "https://github.com/anurag-327/neuron",
        link: "https://neuron-dev.vercel.app/",
        points: [
            "A high-performance, managed code execution engine that lets you run untrusted user code securely and instantly."
        ],
        stack: "Go",
        stack_logo: "https://d26c7l40gvbbg2.cloudfront.net/tool_icons/go.svg",
    },
    {
        id: 2,
        name: "Formwix",
        tag: "A Configuration-based Form Builder for React",
        description: "A configuration-based form builder for React. defined by a single config object, performant, and fully type-safe with Zod validation.",
        toolsused: "React Hook Form, Zod",
        url: "https://formwix-docs.vercel.app/",
        logo: null,
        image: null,
        code: "https://github.com/anurag-327/formwix",
        link: "https://formwix-docs.vercel.app/",
        points: [
            "A dynamic form generation library using React, TypeScript, Zod, and React Hook Form.",
            "Defined by a single config object, performant, and fully type-safe with Zod validation."
        ],
        stack: "React",
        stack_logo: "https://d26c7l40gvbbg2.cloudfront.net/tool_icons/reactjs.svg",
    },
];
